sudo: required

branches:
  only: 
    - master

services:
  - docker

before_install:

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # - npm install
  - version=$(npm version patch -m "v%s [ci skip]")
  - version=$(echo $version | cut -c 2-)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build --build-arg version=version --build-arg DOCKER_USERNAME=$DOCKER_USERNAME --build-arg DOCKER_PASSWORD=$DOCKER_PASSWORD  -t aj03794/raspberry-pi-camera .
  # - docker run aj03794/raspberry-pi-camera /bin/sh -c "npm run test"
  # - docker run aj03794/raspberry-pi-camera /bin/sh -c "./scripts/deploy-docker.sh"
  - docker tag $DOCKER_USERNAME/$IMAGE:latest $DOCKER_USERNAME/$IMAGE:$version
  - docker push $DOCKER_USERNAME/$IMAGE:latest
  - docker push $DOCKER_USERNAME/$IMAGE:$version