sudo: required

branches:
  only: 
    - master

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t test .

script:
  - docker run test /bin/sh -c "npm run test"

before_deploy:
  - docker run test /bin/sh -c "npm run build-babel"
  # Set up git user name and tag this commit
  - git config --local user.name "aj03794"
  - git config --local user.email "adamjohnston151@yahoo.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - cp -r node_modules dist/
  - zip raspberry-pi-camera -r dist/

# deploy:
#   provider: releases
#   api_key: $GITHUB_OAUTH_TOKEN
#   file: dist.zip
#   skip_cleanup: true