sudo: required

language: ruby

cache:
  directories:
    - "node_modules"

services:
  - docker

before_script:
  - docker build -t test .
  # - docker images

before_install:

install:
  - npm install

script:
  - docker run test /bin/sh -c "npm run test"