sudo: required

language: node_js

cache:
  directories:
    - "node_modules"

node_js: 
  - "stable"
services:
  - docker

env:
  global:
    - IMAGE_NAME=armv7/armhf-ubuntu
    - USER_NAME=aj03794

before_script:
  - printenv
  - echo IMAGE_NAME USER_NAME
  - docker pull "$IMAGE_NAME"
  - docker build -t "$USER_NAME"/"$IMAGE_NAME"

before_install:

install:
  - npm install

script:
  - docker run "$IMAGE_NAME" npm test