sudo: required

# language: node_js

services:
  - docker

before_install:
  # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  # - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  # - sudo apt-get update
  # - sudo apt-get -y install docker-ce
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t test .
  # - docker images

script:
  # - docker run test /bin/sh -c "npm run test"
  - exit 0